### ISSUE TITLE
Unordered array should not merge

### ISSUE THREAD

**Issue by schoenwaldnils** [factorial-io/tcm#3]
Unordered array in component arguments should not merge

**Comment by mlnmln** [comment]
+1

We should seriously evaluate the array merging process. I'm currently thinking getting rid of any merge might be beneficial. So we'd end up just with fixtures (for isolation testing) and real parameters for application usage.

**Comment by stmh** [comment]
i am open to suggestions. But be aware we currently do have three arrays in the process:
1. the data defined in the component
2. some settings, defined in the surrounding context e.g. a template file using that component
3. the actual data from the backend.

Perhaps we'd have to separate data from configuration even in the component. Configuration gets merged, data gets replaced.

**Comment by stmh** [comment]
This is now fixed on the develop-branch. I separated configuration from data. Instead of `arguments`  the components can define `options` and `fixture`.

If the components gets no custom data, the fixture is used. Options are handled the old way, they get merged.

Unfortunately the component.son-format has changed, so please port all components over.
